---
version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "rover"
        Alias: "stable"
        CurrentVersion: "1"
        TargetVersion: "2"
