---
version: 0.2

phases:
  install:
    commands:
      - pipenv sync --dev
  build:
    commands:
      - echo Running Python Tests
      - "`pipenv --venv`/bin/python coverage run --omit features/steps/steps.py --source='.' -m behave"
  post_build:
    commands:
      - "`pipenv --venv`/bin/python coverage report > code_coverage.txt"
      - pipenv uninstall --all-dev
      - rm `pipenv --venv`/lib/python3.6/site-packages/boto*
      - rm `pipenv --venv`/lib/python3.6/site-packages/pip*
      - rm `pipenv --venv`/lib/python3.6/site-packages/setuptools*
      - rm `pipenv --venv`/lib/python3.6/site-packages/easy_install*
      - rm `pipenv --venv`/lib/python3.6/site-packages/wheel*
      - echo Build packaged on `date`
artifacts:
  files:
    - code_coverage.txt
    - '**/*.py'
    - '`pipenv --venv`/lib/python3.6/site-packages/**'
  discard-paths: yes
