---
version: 0.2

phases:
  install:
    commands:
      - pipenv sync --dev
  pre_build:
    commands:
      - export PATH=`pipenv --venv`/bin:$PATH
  build:
    commands:
      - echo Running Python Tests
      - coverage run --omit features/steps/steps.py --source='.' -m behave
  post_build:
    commands:
      - coverage report > code_coverage.txt
      - pipenv uninstall --all-dev
      - pipenv uninstall boto3 easy_install pip six wheel
      - rm -rf features
      - echo Build packaged on `date`
artifacts:
  files:
    - code_coverage.txt
    - '**/*.py'
    - '`pipenv --venv`/lib/python3.6/site-packages/**'
